### PR TITLE
replace outdated rust-crypto crate with RustCrypto/hashes

### PR DESCRIPTION
**Pull request by AnderEnder**
Issue: rust-crypto is unmaintained and outdated crate:
- https://www.reddit.com/r/rust/comments/dfm3ya/there_are_231_crates_which_might_depend_on_this/
- https://rustsec.org/advisories/RUSTSEC-2016-0005.html

Implementation: replace  rust-crypto with RustCrypto/hashes/sha2

### CODE REVIEW

**Comment by vaporos** [comment]
Sorry for the delay. This LGTM.

Can you rebase and resolve the conflicts?

**Comment by AnderEnder** [comment]
rebased

**Comment by vaporos** [comment]
Sorry again -- there are more conflicts, please rebase/resolve.

**Comment by peterschwarz** [comment]
Closed, as the changes have been applied in PR #76

**Pull request closed without merging**
